# Load libraries
import flask
from flask import request
import pandas as pd
import tensorflow as tf
import keras
from tensorflow.python.keras.models import load_model
from transformers import AutoModelForSequenceClassification
new_model = AutoModelForSequenceClassification.from_pretrained("./results/")
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
import torch
import numpy as np




finl_a = ['Acebrophylline (100mg)',
 'Aceclofenac (100mg)',
 'Acetazolamide (250mg)',
 'Acetylcysteine (150mg)',
 'Acetylcysteine (600mg)',
 'Acotiamide (100mg)',
 'Acyclovir (400mg)',
 'Ademetionine (400mg)',
 'Albendazole (400mg)',
 'Allopurinol (100mg)',
 'Alpha Lipoic Acid (100mg)',
 'Alpha Lipoic Acid (200mg)',
 'Alprazolam (0.25mg)',
 'Aluminium Hydroxide (0.291gm/5ml)',
 'Ambroxol (15mg)',
 'Ambroxol (15mg/5ml)',
 'Ambroxol (30mg/5ml)',
 'Ambroxol (60mg)',
 'Amitriptyline (10mg)',
 'Amlodipine (5mg)',
 'Ammonium Chloride (125mg/5ml)',
 'Ammonium Chloride (138mg/5ml)',
 'Ammonium Chloride (60mg/5ml)',
 'Amoxycillin  (200mg)',
 'Amoxycillin  (250mg)',
 'Amoxycillin  (500mg)',
 'Amoxycillin (500mg)',
 'Aspirin (150mg)',
 'Aspirin (75mg)',
 'Atorvastatin (10mg)',
 'Atorvastatin (20mg)',
 'Atropine (0.025mg)',
 'Azithromycin (500mg)',
 'Baclofen (10mg)',
 'Beclometasone (0.025% w/w)',
 'Beclometasone (NA)',
 'Benfotiamine (100mg)',
 'Benidipine (8mg)',
 'Benzocaine (2.7% w/v)',
 'Benzyl Nicotinate (2.0mg)',
 'Benzyl Nicotinate (2mg)',
 'Betahistine (16mg)',
 'Betahistine (8mg)',
 'Betamethasone (0.1% w/w)',
 'Betamethasone (0.5mg)',
 'Bethanechol (25mg)',
 'Bilastine (20mg)',
 'Bisoprolol (2.5mg)',
 'Bisoprolol (5mg)',
 'Brivaracetam (50mg)',
 'Bromelain (180mg)',
 'Bromelain (90mg)',
 'Bromhexine (4mg)',
 'Bromhexine (8mg)',
 'Bromhexine (8mg/5ml)',
 'Budesonide (0.5mg)',
 'Budesonide (200mcg)',
 'Buprenorphine (2mg)',
 'Buspirone (10mg)',
 'Caffeine (100mg)',
 'Caffeine (15mg)',
 'Caffeine (30mg)',
 'Calcitriol (0.25mcg)',
 'Calcium Carbonate (500mg)',
 'Calcium Polystyrene Sulphonate (15gm)',
 'Camylofin (25mg)',
 'Carbidopa (25mg)',
 'Carboxymethylcellulose (0.5% w/v)',
 'Cefixime (200mg)',
 'Cefpodoxime Proxetil (200mg)',
 'Ceftriaxone (1000mg)',
 'Ceftriaxone (1gm)',
 'Cefuroxime (500mg)',
 'Cetirizine (10mg)',
 'Cetirizine (5mg)',
 'Cetirizine (5mg/5ml)',
 'Chlorbutol (5% w/v)',
 'Chlordiazepoxide (10mg)',
 'Chlordiazepoxide (5mg)',
 'Chlorhexidine Gluconate (1% w/w)',
 'Chlorpheniramine Maleate (1mg)',
 'Chlorpheniramine Maleate (1mg/5ml)',
 'Chlorpheniramine Maleate (2.5mg/5ml)',
 'Chlorpheniramine Maleate (2mg)',
 'Chlorpheniramine Maleate (2mg/5ml)',
 'Chlorpheniramine Maleate (2mg/ml)',
 'Chlorpheniramine Maleate (4mg/5ml)',
 'Chlorpromazine (25mg)',
 'Chlorpromazine (50mg)',
 'Chlorzoxazone (250mg)',
 'Choline Salicylate (9% w/v)',
 'Cilnidipine (10mg)',
 'Cinnarizine (25mg)',
 'Ciprofloxacin (0.3% w/v)',
 'Ciprofloxacin (500mg)',
 'Clarithromycin (500mg)',
 'Clavulanic Acid (125mg)',
 'Clavulanic Acid (28.5mg)',
 'Clidinium (2.5mg)',
 'Clindamycin (300mg)',
 'Clioquinol (Iodochlorhydroxyquin) (3% w/w)',
 'Clioquinol (Iodochlorhydroxyquin) (NA)',
 'Clobazam (10mg)',
 'Clobazam (5mg)',
 'Clobetasol (0.05% w/w)',
 'Clobetasol (0.5mg)',
 'Clonazepam (0.25mg)',
 'Clonazepam (0.5mg)',
 'Clonidine (100mcg)',
 'Clopidogrel (75mg)',
 'Clotrimazole (1% w/w)',
 'Coenzyme Q10 (100mg)',
 'Coenzyme Q10 (50mg)',
 'Colistin Sulphate (12.5mg)',
 'Cyproterone (2mg)',
 'Dapagliflozin (10mg)',
 'Dapoxetine (30mg)',
 'Deflazacort (6mg)',
 'Desloratadine (5mg)',
 'Desogestrel (0.15mg)',
 'Dexamethasone (0.5mg)',
 'Dextromethorphan Hydrobromide (10mg)',
 'Dextromethorphan Hydrobromide (10mg/5ml)',
 'Dextromethorphan Hydrobromide (15mg/5ml)',
 'Dextromethorphan Hydrobromide (5mg)',
 'Diacerein (50mg)',
 'Diclofenac (100mg)',
 'Diclofenac (50mg)',
 'Dicyclomine (10mg)',
 'Dicyclomine (20mg)',
 'Diethylcarbamazine (100mg)',
 'Diosmin (450mg)',
 'Diosmin (900mg)',
 'Diphenhydramine (12.5mg/5ml)',
 'Diphenhydramine (14.08mg/5ml)',
 'Diphenhydramine (25mg)',
 'Diphenoxylate (2.5mg)',
 'Disulfiram (250mg)',
 'Domperidone (10mg)',
 'Domperidone (20mg)',
 'Domperidone (30mg)',
 'Doxofylline (400mg)',
 'Doxycycline (100mg)',
 'Doxylamine (10mg)',
 'Drospirenone (3mg)',
 'Drotaverine (80mg)',
 'Dutasteride (0.5mg)',
 'Dydrogesterone (10mg)',
 'Ebastine (10mg)',
 'Empagliflozin (10mg)',
 'Empagliflozin (12.5mg)',
 'Empagliflozin (25mg)',
 'Ergotamine (1mg)',
 'Escitalopram Oxalate (10mg)',
 'Escitalopram Oxalate (5mg)',
 'Esomeprazole (40mg)',
 'Ethinyl Estradiol (0.02mg)',
 'Ethinyl Estradiol (0.035mg)',
 'Ethinyl Estradiol (0.03mg)',
 'Ethinyl Estradiol (0.05mg)',
 'Etizolam (0.25mg)',
 'Etizolam (0.5mg)',
 'Etodolac (400mg)',
 'Etofylline (115mg)',
 'Etofylline (77mg)',
 'Etoricoxib (60mg)',
 'Etoricoxib (90mg)',
 'Famotidine (40mg)',
 'Faropenem (200mg)',
 'Febuxostat (40mg)',
 'Fexofenadine (120mg)',
 'Fexofenadine (30mg/5ml)',
 'Finasteride (1mg)',
 'Flavoxate (200mg)',
 'Fluconazole (150mg)',
 'Flunarizine (10mg)',
 'Fluoxetine (20mg)',
 'Flupenthixol (0.5mg)',
 'Fluticasone Propionate (250mcg)',
 'Folic Acid (15mg/ml)',
 'Folic Acid (5mg)',
 'Formoterol (20mcg)',
 'Formoterol (6mcg)',
 'Furosemide (20mg)',
 'Furosemide (40mg)',
 'Fusidic Acid (2% w/w)',
 'Gabapentin (100mg)',
 'Gabapentin (400mg)',
 'Gentamicin (0.1% w/w)',
 'Gentamicin (1mg)',
 'Glimepiride (1mg)',
 'Glimepiride (2mg)',
 'Glipizide (5mg)',
 'Glucosamine (750mg)',
 'Guaifenesin (100mg/5ml)',
 'Guaifenesin (50mg)',
 'Guaifenesin (50mg/5ml)',
 'Heparin (50IU)',
 'Hesperidin (100mg)',
 'Hesperidin (50mg)',
 'Human Insulin/Soluble Insulin (30%)',
 'Human chorionic gonadotropin (hCG) (5000IU)',
 'Human insulin (40IU)',
 'Hydralazine (37.5mg)',
 'Hydrochlorothiazide (12.5mg)',
 'Hydroquinone (2% w/w)',
 'Hydroxychloroquine (200mg)',
 'Hydroxyzine (10mg)',
 'Hydroxyzine (25mg)',
 'Hyoscine butylbromide (10mg)',
 'Hyoscyamine (0.125mg)',
 'Ibuprofen (100mg)',
 'Ibuprofen (400mg)',
 'Ibuprofen (600mg)',
 'Indomethacin (75mg)',
 'Insulin Isophane/NPH   (70%)',
 'Ipratropium (500mcg)',
 'Isosorbide Dinitrate (20mg)',
 'Isosorbide Dinitrate (5mg)',
 'Isosorbide Mononitrate (30mg)',
 'Isotretinoin (20mg)',
 'Isoxsuprine (10mg)',
 'Itopride (50mg)',
 'Itraconazole (200mg)',
 'Ivabradine (5mg)',
 'Ivermectin  (6mg)',
 'Ketoconazole (2% w/v)',
 'Ketoconazole (2% w/w)',
 'Ketorolac (10mg)',
 'L-Ornithine L-Aspartate (150mg)',
 'Lactobacillus (120Million spores)',
 'Lactobacillus (5Billion Spores)',
 'Lactulose (3.335gm/5ml)',
 'Lansoprazole (15mg)',
 'Lansoprazole (30mg)',
 'Letrozole (2.5mg)',
 'Levetiracetam (500mg)',
 'Levo-carnitine (150mg)',
 'Levo-carnitine (500mg)',
 'Levocetirizine (2.5mg/5ml)',
 'Levocetirizine (5mg)',
 'Levocloperastine (20mg/5ml)',
 'Levodopa (100mg)',
 'Levodropropizine (30mg/5ml)',
 'Levofloxacin (500mg)',
 'Levonorgestrel (0.15mg)',
 'Levosalbutamol (0.5mg)',
 'Levosalbutamol (0.5mg/5ml)',
 'Levosalbutamol (0.63mg)',
 'Levosalbutamol (1.25mg)',
 'Levosalbutamol (1mg/5ml)',
 'Lidocaine (1.5% w/w)',
 'Lidocaine (10% w/v)',
 'Lidocaine (2% w/v)',
 'Lidocaine (2% w/w)',
 'Lidocaine (2%)',
 'Linagliptin (2.5mg)',
 'Linagliptin (5mg)',
 'Linezolid (600mg)',
 'Liquid Paraffin (1.25ml)',
 'Live Freeze Dried Lactic Acid Bacteria and Bifidobacteria (112.5Billion CFU)',
 'Loperamide (2mg)',
 'Magaldrate (400mg/5ml)',
 'Magaldrate (480mg)',
 'Magaldrate (540mg)',
 'Medroxyprogesterone acetate (10mg)',
 'Mefenamic Acid (100mg/5ml)',
 'Mefenamic Acid (250mg)',
 'Mefenamic Acid (500mg)',
 'Melitracen (10mg)',
 'Memantine (5mg)',
 'Metaxalone (400mg)',
 'Metformin  (500mg)',
 'Metformin (1000mg)',
 'Metformin (500mg)',
 'Methylcobalamin (1000mcg)',
 'Methylcobalamin (1500mcg)',
 'Metoclopramide (10mg)',
 'Metoprolol Succinate (23.75mg)',
 'Metoprolol Succinate (47.5mg)',
 'Metronidazole (200mg/5ml)',
 'Metronidazole (400mg)',
 'Mirabegron (50mg)',
 'Mometasone (0.1% w/w)',
 'Montelukast (10mg)',
 'Montelukast (4mg/5ml)',
 'Mupirocin (2% w/w)',
 'Naloxone (0.5mg)',
 'Naproxen (500mg)',
 'Neomycin (0.5% w/w)',
 'Neomycin (3500u/1g)',
 'Nicorandil (5mg)',
 'Nicotinamide (200mg/ml)',
 'Nifedipine (0.3% w/w)',
 'Nifedipine (20mg)',
 'Nimesulide (100mg)',
 'Nitrofurantoin (100mg)',
 'Norethisterone (5mg)',
 'Norfloxacin (400mg)',
 'Norgestrel (0.5mg)',
 'Nortriptyline (10mg)',
 'Ofloxacin (100mg/5ml)',
 'Ofloxacin (200mg)',
 'Olopatadine (0.1% w/v)',
 'Omeprazole (20mg)',
 'Ondansetron (2mg/5ml)',
 'Ondansetron (4mg)',
 'Ornidazole (500mg)',
 'Oseltamivir Phosphate (75mg)',
 'Oxetacaine (10mg/5ml)',
 'Pancreatin (100mg)',
 'Pancreatin (170mg)',
 'Pantoprazole (20mg)',
 'Pantoprazole (40mg)',
 'Paracetamol (125mg)',
 'Paracetamol (125mg/5ml)',
 'Paracetamol (162.5mg)',
 'Paracetamol (300mg)',
 'Paracetamol (325mg)',
 'Paracetamol (500mg)',
 'Paracetamol (650mg)',
 'Paracetamol (700mg)',
 'Paracetamol/Acetaminophen  (162.5mg)',
 'Paracetamol/Acetaminophen  (325mg)',
 'Paradichlorobenzene (2% w/v)',
 'Pentoxifylline (400mg)',
 'Pheniramine (25mg)',
 'Phenobarbitone (50mg)',
 'Phenylephrine (0.10% w/w)',
 'Phenylephrine (10mg)',
 'Phenylephrine (5mg)',
 'Phenylephrine (5mg/5ml)',
 'Phenylephrine (5mg/ml)',
 'Phenytoin (100mg)',
 'Piroxicam (20mg)',
 'Povidone Iodine (2% w/v)',
 'Prednisolone (10mg)',
 'Prednisolone (20mg)',
 'Prednisolone (40mg)',
 'Prednisolone (5mg)',
 'Prednisolone (5mg/5ml)',
 'Pregabalin (75mg)',
 'Prochlorperazine (5mg)',
 'Progesterone (Natural Micronized) (200mg)',
 'Promethazine (25mg)',
 'Promethazine (5mg/5ml)',
 'Propranolol (10mg)',
 'Propranolol (20mg)',
 'Propranolol (40mg)',
 'Quetiapine (100mg)',
 'Quetiapine (25mg)',
 'Quetiapine (50mg)',
 'Quiniodochlor (250mg)',
 'Rabeprazole (20mg)',
 'Racecadotril (100mg)',
 'Ranitidine (150mg)',
 'Ranitidine (300mg)',
 'Rifaximin (400mg)',
 'Rifaximin (550mg)',
 'Rivaroxaban (10mg)',
 'Rivaroxaban (15mg)',
 'Rivaroxaban (20mg)',
 'Rosuvastatin (10mg)',
 'Roxithromycin (150mg)',
 'Saccharomyces boulardii (250mg)',
 'Sacubitril (24mg)',
 'Sacubitril (49mg)',
 'Safinamide (50mg)',
 'Salbutamol (1mg/5ml)',
 'Salbutamol (2mg/5ml)',
 'Salbutamol (4mg)',
 'Salmeterol (25mcg)',
 'Saroglitazar (4mg)',
 'Saxagliptin (5mg)',
 'Serratiopeptidase (10mg)',
 'Sildenafil (100mg)',
 'Sildenafil (50mg)',
 'Sildenafil (NA)',
 'Simethicone (20mg)',
 'Simethicone (20mg/5ml)',
 'Simethicone (50mg)',
 'Sitagliptin  (100mg)',
 'Sitagliptin  (50mg)',
 'Sitagliptin (100mg)',
 'Sitagliptin (50mg)',
 'Sodium Chloride (3% w/v)',
 'Sodium Hyaluronate (0.18% w/v)',
 'Sodium Picosulfate (3.33mg)',
 'Sodium Tauroglycocholate (65mg)',
 'Solifenacin (5mg)',
 'Sorbitol (7.15gm)',
 'Spironolactone (50mg)',
 'Sultamicillin tosilate (375mg)',
 'Sumatriptan (85mg)',
 'Tadalafil (10mg)',
 'Tadalafil (2.5mg)',
 'Tadalafil (5mg)',
 'Tamsulosin  (0.4mg)',
 'Tamsulosin (0.4mg)',
 'Taurine (500mg)',
 'Tazobactum (125mg)',
 'Telmisartan (40mg)',
 'Terbinafine (1% w/w)',
 'Terbutaline (2.5mg/5ml)',
 'Theophylline (23mg)',
 'Theophylline (35mg)',
 'Theophylline (400mg)',
 'Thiamine(Vitamin B1) (100mg)',
 'Thiocolchicoside (4mg)',
 'Thyroxine (25mcg)',
 'Ticagrelor (90mg)',
 'Tinidazole (500mg)',
 'Tinidazole (600mg)',
 'Tizanidine (2mg)',
 'Torasemide (10mg)',
 'Tramadol (18.75mg)',
 'Tramadol (37.5mg)',
 'Tranexamic Acid (500mg)',
 'Tretinoin (0.025% w/w)',
 'Triamcinolone (0.1% w/w)',
 'Triamcinolone (40mg/ml)',
 'Tricholine Citrate (0.55gm)',
 'Trihexyphenidyl (2mg)',
 'Trimetazidine (35mg)',
 'Trypsin (48mg)',
 'Trypsin (96mg)',
 'Trypsin Chymotrypsin (100000AU)',
 'Ulipristal acetate (5mg)',
 'Ursodeoxycholic Acid (150mg)',
 'Ursodeoxycholic Acid (300mg)',
 'Valsartan (26mg)',
 'Valsartan (51mg)',
 'Vildagliptin (100mg)',
 'Vildagliptin (50mg)',
 'Vitamin B6 (Pyridoxine) (100mg)',
 'Vitamin B6 (Pyridoxine) (10mg)',
 'Vitamin B6 (Pyridoxine) (5mg)',
 'Vitamin D3 (60000IU)',
 'Vitamin E (200mg)',
 'Warfarin (5mg)',
 'Zinc pyrithione (1% w/v)',
 'Zolpidem (10mg)',
 'Zolpidem (5mg)',
 'drolone Decanoate (50mg)']

dict_map ={}
for index,tag in enumerate(finl_a):
    dict_map[tag] = index
# print(dict_map)
inverted_dict = dict(zip(dict_map.values(), dict_map.keys()))
# print(inverted_dict)


# instantiate flask 
app = flask.Flask(__name__)

# model_path = "D:/neural networks/DeepAudioProjects/Capuchin Calls/maybefinal.h5"
# model = load_model(model_path)
def get_prediction(text):
  encoding =tokenizer(text,return_tensors="pt",padding="max_length",truncation=True,max_length=512)
  encoding = {k: v.to("cpu") for k,v in encoding.items()}

  outputs = new_model(**encoding)
  logits = outputs.logits
  softmax = torch.nn.Softmax()
  probs = softmax(logits.squeeze().cpu())
  probs = probs.detach().numpy()
  top_3_indices = np.argpartition(probs, -3)[-3:]
  # top_3_values = probs[top_3_indices]

  # print(top_3_indices)
# print(top_3_values)
  top_3_values = [inverted_dict[item] for item in top_3_indices]
  # labels = np.argmax(probs,axis=-1)
  return {"tags":top_3_values}
# def serve_model():
#     request_data = request.get_json(force=True)
#     # request_data
#     file = request_data["audio_file"]
#     return ("Prediction is {}".format(request_data["class"]))
get_prediction("dolo 650 tablet")
@app.route("/model",methods=["POST"])
def get_prediction(text):
  encoding =tokenizer(text,return_tensors="pt",padding="max_length",truncation=True,max_length=512)
  encoding = {k: v.to("cpu") for k,v in encoding.items()}

  outputs = new_model(**encoding)
  logits = outputs.logits
  softmax = torch.nn.Softmax()
  probs = softmax(logits.squeeze().cpu())
  probs = probs.detach().numpy()
  top_3_indices = np.argpartition(probs, -3)[-3:]
  # top_3_values = probs[top_3_indices]

  # print(top_3_indices)
# print(top_3_values)
  top_3_values = [inverted_dict[item] for item in top_3_indices]
  # labels = np.argmax(probs,axis=-1)
  print({"tags":top_3_values})
# def serve_model():
#     request_data = request.get_json(force=True)
#     # request_data
#     file = request_data["audio_file"]
#     return ("Prediction is {}".format(request_data["class"]))

if __name__ == "__main__":
    get_prediction("dolo 650 tablet")
    app.run()
